apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: action-messages-hpa
  namespace: techpathway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: action-messages
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: techpathway-warehouse-hpa
  namespace: techpathway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techpathway-warehouse
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: weekly-call-hpa
  namespace: techpathway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weekly-call
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50